.github/workflows/compile-mermaid.yml

It is hard to use github package registry at the moment, because users cannot download docker images anonymously. Therefore, we implemented an extra step in the build and test action to also publsih to docker.io.

Publish to docker com

---

src-test/test.js
src/index.js
test/invalid.expect-error.mmd
todo.md

Present nice error message when mermaid source cannot be parsed.
It seems that the mermaid package's parse error overrides `Error::message`. This means it's necessary to catch the error within the browser context, so we can call `error.message` at that point. Otherwise, the formatting logic would need to be duplicated in this cli.
This change is not just for cleaner output&mdash;node currently fails the script with an "UnhandledPromiseRejectionWarning", and warns that this will not be supported in the future.
I needed to modify the test script, as I now have a case that _expects_ an error. The implementation of that code is as clear as I could make it, but I'd love suggestions on how to improve it.
Also, I wasn't able to run the tests locally. Not 100% sure that they worked.
Make sure you

Try catch to avoid unhandled rejection

---

src/index.js

This patch adjust the PDF page size in order to fit the chart dimension.
(ported from https://github.com/mermaidjs/mermaid.cli/pull/53)
Currently PDFs produced by the tool have a fixed page size, independent from the chart size and dictated by the internal behavior of Puppeteer (the documentation says that in the absence of specific options the page size is always Letter).
This produces pages with excessive blank spaces (as mentioned in #48) and is also an anomaly with respect to results obtained with other output formats, since both SVGs and PNGs do fit perfectly the chart size.
This patch adjust the PDF page size in order to fit the chart dimension, also including the margins automatically added by Chromium, resulting in PDFs without blank spaces.
The patch has been tested with all the …

Adjust PDF page size to fit chart size

---

.github/pr-labeler.yml
.github/release-drafter.yml

We would like a better release note, where all PRs made by dependebot are grouped and placed at the bottom of the release note.
Make sure you
- [+] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [+] :computer: have added unit/e2e tests (if appropriate) 
- [+] :bookmark: targeted `master` branch

Group dependebot Pull Requests

---

.github/workflows/release-publish.yml

In the v2 of `actions/checkout`, setting the token is no longer necessary, so I created a new config-less action to just set the git user: https://github.com/fregante/setup-git-user

Replace `fregante/setup-git-token` with `setup-git-user`

---

.github/workflows/compile-mermaid.yml
run-tests.sh

Percy testing framework does not support svgs. In some cases, we want to export svgs and see that working.

Install convert-svg-to-png for e2e testing

---

package.json

The last version set in package.json for mermaid is 8.8.1, while the last released mermaid version is 8.8.4.
For whatever reason dependebot did not update package.json with the new mermaid versions.

Bump mermaid to 8.8.4

---

.github/workflows/compile-mermaid.yml
run-tests.sh
src/index.js
test-positive/graph-with-br.mmd

See issue #74 
`<br>` tags are valid HTML, but SVG requires valid XML (where `<br>` is written `<br/>`)
I'm sorry, but I'm new to node and I haven't been able to test this commit :-(
(after `yarn` and `source copy_modules.sh`, the doc instructs me to run `node index.bundle.js -i test/state1.mmd` but there is no `index.bundle.js`, I have no idea whether it is actually missing or whether I have failed to generate it).
A test case is described in the linked issue in case you want to test it yourself (but I'd be happy someone tells me what I am missing to test this)

Properly handling <br> tags

---

src/index.js
test-positive/no-charts.md

- Fix exception in case no charts were found in Markdown file
- Log depending on type of input (Markdown or mermaid): Number of charts
found in Markdown file
- Add --quiet flag to suppress these new log message
`String.match` returns null if nothing was matched - the PR fixes handling this case.
Also adds more log output that can be suppressed with `-q/--quiet`.
Explains in description for `--input` flag how .md files are treated.
Resolves #160
Calling mermaid-cli on a Markdown file that does not contain mermaid charts should not crash the application. Neither should it report an error or return a non-null status code as it might break use cases where someone blindly runs it on a collection of Markdown files.
I did not apply the standard.js linter/formatter as the existing code base is …

Fix Markdown parsing, add more verbose output

---

run-tests.sh

Add an automated test for #165 
Resolves #166 
I simply run mmdc in a container, verify it doesn't crash and then compare its output to an expected value.
I'm not quite happy with this setup, as run_tests.sh is meant to be called with either test-positive or test-negative - this new test will run in both cases. I'd suggest removing the INPUT_DATA argument and hard-coding test-positive and test-negative.
Make sure you

Add test for #165

---

.gitattributes
src/index.js
test-positive/crlf-detect.md

Add optional CR to markdown graph detection regex.
Add test CRLF markdown file.
Add .gitattributes to prevent git from converting CRLF to LF in test file.
Resolves #183

Add optional CR to markdown graph detection regex.

---

.gitignore
README.md
src-test/test.js
src/index.js
test-positive/markdown-output.md

Allow a *.md file as output (provided with `-o`).
Resolves #154
It only works when the input is a *.md file as well. It will replace all mermaid-js diagrams in a markdown files with images.
This:
~~~md
```mermaid
graph
[....]
```
~~~
Becomes:
```md
```
It currently uses the output file name to base the image file names on. I.e. if "out.md". use "out-1.svg", "out-2.svg", etc. We can add support for other output file formats later by adding command line arguments. I was thinking about something like `--outputImage` for example.
Make sure you

feat(md output): allow *.md files in output

---

src/index.js

replaceAll is supported in nodejs >= 15. replace is supported since node 0.10.0 and does the same thing, except that it does not enforce that you use the regex global flag.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#browser_compatibility
Allow more global compatibility.
Make sure you

Replace replaceAll with replace for node 14 support

---

src-test/test.js
src/index.js

Output svg's have a transparent background which doesn't look good against github's dark mode themed pages. Set the background-color in the style tag of the svg to set the background color to white (default) or whatever a user chooses with the -b option.
Resolves some user requests in this ticket: https://github.com/mermaid-js/mermaid/issues/1553
Shouldn't crash. Tests pass.
Make sure you

Add background color style to output svg's

---

README.md

Fix the docker image paths in README
Make sure you

Fix the docker image paths in README

---

src-test/test.js
src/index.js
test-negative/puppeteerTimeoutConfig.json

Currently, some errors in `mermaid-cli` cause an `UnhandledPromiseRejectionWarning`, and `mermaid-cli` then exits with `exitcode 0` instead of `exitcode 1`.
For example, if `puppeteer.launch` fails for any reason, there's nothing `.catch()`-ing the Promise rejection https://github.com/mermaid-js/mermaid-cli/blob/6fa464418488ead911faa2537ed4e2c33fc267f1/src/index.js#L218 are not caught anywhere.
I've added a `.catch()` block that logs the error (hiding the `UnhandledPromiseRejectionWarning`), then calls `process.exit(1)` to set the exitcode to 1.
I've added a test that sets puppeteer's launch timeout to 1ms, which should always cause an error. Before my PR, this causes `mmdc` to return with `exitcode == 0` (success) instead of returning with `exitcode == 1` (error).
Alternatively, you can …

Exit with exitcode = 1 on promise rejection

---

src-test/test.js
src/index.js

Currently, if an input is not specified, `commander.help()` is called, which outputs the help text to stdout, and exits with `exitcode = 0`. The `process.exit(1)` line is never reached.
The `{error: true}` option can instead be used to output the help to stderr, and exit with an error exitcode, see: https://github.com/tj/commander.js#display-help-from-code
Make sure you

Exit with error exitcode on invalid input

---

src-test/test.js
src/index.js

~**Draft until #350 is merged, since I didn't want a merge conflict.** I'm leaving this here open for review since it fixes #348.~
Currently, Mermaid only supports using png as a output when using markdown as an input, e.g. `-i markdown.md -o hi.png` will output:
`hi-1.png`, `hi-2.png`, ...
This PR adds support for `svg` and `pdf`.
This means that when running `-i markdown.md` with no `-o` output arg, the default `.svg` will be used to output
`markdown.md-1.svg`, `markdown.md-2.svg`, ...
**Resolves #348**
(All images have the same filename, so overwrite each other)
The actual change is only one line: https://github.com/mermaid-js/mermaid-cli/commit/4dc31257e567102c6f1fd9c7187fee0588577a17
I've made this PR on top of #350 just to avoid a merge conflict in the test code.
If #350 doesn't get …

Support SVG/PDF template files for markdown input

---

README.md
building.md
package.json
src-test/test.js
src/cli.js
src/index.js

Sorry, one last PR for you to review @MindaugasLaganeckas!
Instead of just using the mmdc CLI, this PR will make it possible to run mermaid-cli from a NodeJS API, e.g.
```js
import { run } from "@mermaid-js/mermaid-cli"
await run("input.mmd", "output.svg", /* {optional options} */)
```
**BREAKING CHANGE**: The CLI (mmdc) entry to this module is now `src/cli.js`. This shouldn't be a big deal, since it was already changed to `src/index.js` in #350.
This will make testing easier, and allow nodejs packages to call `mmdc` directly, which should simplify a lot of people's code, e.g. see:
- https://github.com/mermaid-js/mermaid-cli/issues/271#issue-1186458762
- https://github.com/mermaid-js/mermaid-cli/issues/247
- https://github.com/mermaid-js/mermaid-cli/issues/154#issuecomment-989828463
- My …

feat: add NodeJS API to mermaid-cli

---

.github/workflows/compile-mermaid.yml

Updates Percy to use the new SDK
Currently, Percy has a warning that says **Heads up! The SDK used in this build is deprecated and no longer supported. [You can find SDK instructions to upgrade your SDK here.](https://docs.percy.io/docs/migrating-to-percy-cli)**
Copied from https://docs.percy.io/docs/github-actions
I'm 95% sure this will work, but to test, it might be worth moving this branch into your repo, since the PERCY_TOKEN is private, and won't work on forks (like this PR).
Make sure you

ci: update percy upload action

---

.github/workflows/compile-mermaid.yml
docs/reviewing.md

The `pull_request_target` event does have access to the repository secrets, but this is because it doesn't run on the fork contents.
Instead, it runs on the target of the PR, e.g. when somebody makes a PR, instead of testing/running on their fork's `feature/...` branch, it runs on `mermaid-cli`'s `master` branch, which hasn't been changed.
Unfortunately, **there's no easy way to give forks access to our GitHub Actions secrets,** because if there was, they could just do `"echo "$MY_SECRET"` and they'll see the secret.
Instead, there are three things we can do:
- :heavy_check_mark: (what I documented in this PR)
Manually make a copy of the fork branch in this repo (after reviewing first so there are no security issues)
- :question: Make `PERCY_TOKEN` public.
I'm not 100% sure this is safe …

ci: fix percy ci action

---

.github/workflows/compile-mermaid.yml
run-tests.sh
src-test/test.js
src/index.js
test-positive/flowchart1.css

If a `--cssFile` is given to mermaid-cli, adds it as a `<svg><style>` node. This means it's part of the `<svg>` and will get exported correctly when creating a SVG file.
See https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement for documentation on the WebAPI on the `<svg><style>` element.
Fixes #55, fixes #270
I've taken content from the following PRs, so I've added the authors as `Co-authors`:
- Resolves #60
- Resolves #119
- Resolves #194
Example: `test-output/flowchart1-with-css.svg`:
<details>
<summary>`flowchart1-red-background.svg`</summary>
- SVG ![flowchart1-red-background](https://user-images.githubusercontent.com/19716675/185466191-4259aa1a-a520-4f9d-954f-2a0e0cc2457b.svg)
- PNG ![flowchart1-red-background](https://user-images.githubusercontent.com/19716675/185466334- …

Add `--cssFile` as `<style>` node to SVG

---

.github/workflows/release-publish.yml
.github/workflows/test.yml
CONTRIBUTING.md
DockerfileBuild
building.md
copy_modules.sh
install-dependencies.sh
package.json
run-tests.sh

Lints this project using [`standard`](https://standardjs.com/).
I've added running `standard` to the `package.json#scripts#test` (in https://github.com/mermaid-js/mermaid-cli/pull/313/commits/b1fda2004618e7c358787a058b843bd902ff33da), since that's what it says in `CONTRIBUTING.md`:
https://github.com/mermaid-js/mermaid-cli/blob/6fa464418488ead911faa2537ed4e2c33fc267f1/CONTRIBUTING.md?plain=1#L23
~I've also added a GitHub Actions CI action that runs `yarn test` automatically for future PRs in https://github.com/mermaid-js/mermaid-cli/commit/34017714315dd1577e16610e1669aab7e7b0d228.~ Already added by https://github.com/mermaid-js/mermaid-cli/commit/9c15b9d8cded5430e934cb9b90a8bdad83cb32d8 in `master`.
~Finally, I've fixed any errors that were NOT automatically fixed by `standard --fix` in …

Lint using `standard`

---

.github/workflows/compile-mermaid.yml
.github/workflows/upload-percy.yml

Uploading to Percy from a `pull_request` GitHub Action fails from forks, since they do not have access to our private `${{ secrets.PERCY_TOKEN }}` variable.
However, according to GitHub's official docs, (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) we can have a `workflow_run` action that automatically runs after the `pull_request` action, and that can have access to the `secrets.PERCY_TOKEN`
folder.
I think this resolves #364, but to test this, we'll have to make another PR after this PR is merged (I have https://github.com/aloisklink/mermaid-cli/pull/2 ready to go)
Make sure you

ci: fix percy CI upload from forks

---

test-positive/custom-init-config.mmd

Mermaid supports adding options by using `%%init%%`.
This test also uses a font-awesome symbol, so it tests for that too.
According to https://github.com/mermaid-js/mermaid-cli/issues/341, this was broken in v0.5.1, although it works in the v9.1.4 version.
Example copied from https://mermaid-js.github.io/mermaid/#/./theming?id=customizing-themes-with-themevariables
This is a very small PR. I've mainly made it to confirm that the new Percy upload action from forks works (added in #366).
Make sure you

test: add a test case for inline `%%init%%`

---

src/index.js

Wraps the `parseMMD` function in a `try ... finally ...` block to automatically run puppeteer's `page.close()` function when `parseMDD` exits.
It's very minor, since normally mermaid-cli exits very quickly, but on the off chance somebody is using `mermaid-cli` on a giant markdown file with 100s of diagrams (e.g. a book using Pandoc), then this will improve their memory usage.
Because the entire `parseMDD` function has been indented, the `git diff` is a bit complicated. Let me know if you want me to split it up into two commits to make reviewing easier:
- `fix: close parseMMD page memory leak`
- `style: fix parseMMD indentation`
Make sure you
- Not added, since the bugfix is pretty straightforward (and unit tests for memory leaks will be very hard in JavaScript)

Close `parseMMD` puppeteer page memory leak

---

docs/animated-flowchart.svg
test-positive/flowchart1.css

Currently, the `flowchart1-with-css-{svg,png}.png` file is constantly animated. Since there is a slight bit of random delay when converting this animated SVG to a static picture, each PNG file is slightly different, causing Percy to throw an error, showing that the files have changed slightly.
Example Percy errors:
- https://percy.io/Mermaid/mermaid-cli/builds/21195151/changed/1182895944?browser=chrome&browser_ids=22%2C23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=313&widths=313
This commit makes the animated SVG static for the first 3 seconds, allowing for `mermaid-cli` and `convert-svg-to-png` to always take the same snapshot.
The animation is only paused for the first 3 seconds, but from my basic testing, this seems to be fine and the output …

test: make animated SVG static for first 3seconds

---

src-test/test.js
src/index.js
test-positive/mermaid.md

Signed-off-by: Andreas Ulm <andreas.ulm@skaylink.com>
* detect indented mermaid codeblocks in MD (#317)
* detect space suffixed mermaid codeblocks in MD (#342)
Resolves #317 
Resolves #342 
Extended regular expression `mermaidChartsInMarkdown` with optional any number of spaces before and after codeblock fences.
Extended test case `should write multiple SVGs for default .md input by default` to include markdown code that has spaces. (10. = indented, 11. = spaces appended)
Make sure you

fix: detect spaced codeblocks (#317 #342)

---

run-tests.sh
test-positive/config-noUseMaxWidth.json

Mermaid v9.1.7 implemented commit https://github.com/mermaid-js/mermaid/commit/2968b400c49f66983e6d206959504e72aa6ae0ef that removes the `width` attr from SVGs by default, using the CSS `max-width` style instead.
Percy CI (used for visual regression tests) does not yet support SVGs, so we use convert-svg-to-png@v0.5.0, but that requires either the width or the height to calculate the size of the PNG to convert to SVG to.
To fix this, the Mermaid `useMaxWidth` option can be set to `false`. Annoyingly, we need to do this for every single graph type, see https://mermaid-js.github.io/mermaid/#/Setup?id=usemaxwidth
Should fix the failing CI in PR #383.
N/A
Make sure you

ci(test): fix convert-svg-to-png in mermaid 9.1.7

---

src-test/test.js
test-positive/mermaid.md

Cleans up the `test-positive/mermaid.md` file
The mermaid syntax in the file was technically incorrect, and some mermaid parsers (VS Code) were throwing an error due to the \`\`\` characters.
I delete the `indented.mmd` and `space-appended.mmd` lines, since there are no `indented.mmd` and/or `space-appended.mmd` files (these tests are just to check markdown rendering rules).
I've also moved the comment into the ```` ```mermaid ``` ```` code-block, since Mermaid supports comments, but Markdown doesn't.
Make sure you

test(mermaid.md): cleanup mermaid.md test case

---

README.md
src-test/test.js
src/index.js
test-positive/mermaid.md

Loads the title and/or description text from the Mermaid SVG for accessibility purposes.
In come countries, it is illegal to use images on a website without the appropriate alt text. Additionally, some markdown renderers use the alt text as a caption (e.g. Pandoc).
The following mermaid code:
````markdown
```mermaid
stateDiagram
accTitle: State diagram title here
accDescr: State diagram description here
state Choose <<fork>>
Choose --> Still
```
````
aka (has `<title />` and `<desc/>` for people on screen readers)
```mermaid
stateDiagram
accTitle: State diagram title here
accDescr: State diagram description here
state Choose <<fork>>
Choose --> Still
```
Will get converted to the following markdown image:
```markdown
```
`[]` in the alt text and `"` in the title text are automatically …

feat: load title/desc text from Mermaid SVG

---

src-test/test.js
src/index.js

Fixing  `-e` flag option to place output format to the file.
Resolves #394 
Added an `if` statement to check if `-e` flag is given. If so then the extension is added to the output file by assigning the `output` variable with the extension specified. Also added additional tests to see if the logic is working. 
Make sure you

Fixed -e flag option to place output format for files

---

package.json
src-test/test.js
yarn.lock

Bumps [mermaid](https://github.com/mermaid-js/mermaid) from 9.1.7 to 9.2.2.
- [Release notes](https://github.com/mermaid-js/mermaid/releases)
- [Commits][1]
[1]: https://github.com/mermaid-js/mermaid/compare/9.1.7...9.2.2
The tests needed to be modified slightly, since the following error is now thrown for our invalid mermaid file test:
```
Error: No diagram type detected for text: ...
```
Co-authored-by: Mindaugas Laganeckas <mindaugas.laganeckas@gmail.com>
**This does not add `mermaid-mindmap` support, I'll add that in another PR.**
Make sure you

chore(deps-dev): bump mermaid from 9.1.7 to 9.2.2

---

.gitignore
copy_modules.sh
index.html
package.json
src/index.js
test-positive/mindmap.mmd
vite.config.ts
yarn.lock

Adds support for rendering mermaid mindmaps using the `@mermaid-js/mermaid-mindmap` plugin.
Unfortunately, because the `@mermaid-js/mermaid-mindmap` plugin uses dynamic ESM imports (e.g. `const ... = await import("example.js")`, puppeteer throws a CORS error when trying to import it.
I tried using the official way to disable this, https://pptr.dev/api/puppeteer.page.setbypasscsp, but it still seemed like I couldn't load `@mermaid-js/mermaid-mindmap` dynamically.
To get around this, I've had to use `vite` to bundle the `index.html` code (the same bundler that is used in the `mermaid` and `mermaid-live-editor` projects).
Basically, it combines the fontawesome fonts, the `mermaid.js` and the `mermaid-mindmap.js` files into one `index.html` file.
This has a few other benefits:
- we can remove …

Add `@mermaid-js/mermaid-mindmap` support

---

README.md

`npm i -g` is working and is the recommended approach for most node cli tools now.
I think the permission issues happen when people run it as root and all. 
https://github.com/antfu/ni
https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable
Bring the installation instruction to the top so people don't use outdated methods like brew.
Make sure you

Update README.md to highlight install step

---

Dockerfile

As discussed in #435 
The patch does NOT change the workdir.

Use an absolute path for the docker entrypoint

---

README.md

* the `-it` flag is used when you want an interactive shell, it is useless in this context
* the `--rm` flag will remove the container after the job is done, this is very important because it will save a lot of space on the end user's computer
* the `-u` defines the user id that will be used inside the container, this is really convenient because the output files will belong to the user who launches docker
As a comparison, here how you launche the pandoc docker image:
```
docker run --rm --volume "`pwd`:/data" --user `id -u`:`id -g` pandoc/latex:2.6 README.md
```
see https://github.com/pandoc/dockerfiles#basic-usage

Improvement the docker command line example

---

src/index.js

Removes commander deprecated arguments, and removes duplicate ```default: 800 (default: 800)``` `--help` text.
This change should not change anything when using mermaid-cli. All it will do is:
a) improve the `--help` message
b) improve error messages when using the wrong types/values
Because I've removed the `regex` for `--width` and `--height`, passing things like `--width 12.3` is now valid, but `parseInt` will silently convert this to `12`. I'm not really sure if JavaScript has any good built-in functions for strictly parsing integers though. However, this is what the commander docs recommend, see https://github.com/tj/commander.js#custom-option-processing
Using regex in Commander directly is deprecated since Command v7, see https://github.com/tj/commander.js/blob/82fcb98cc27164a98e0c5f …

Refactor commander CLI options

---

package.json

Update compatible version of node-js as required by chalk and puppeteer
I had found that node-js 14.1 does not work. As per discussion on mermaid slack, `puppeteer` requires >= 14.1.0 but this is superseded by `chalk` which only allows 14.13, or >=16.0.0.
A brief change to `package.json` for which version of node-js are allowed.
N/A
Make sure you

Correct compatible Node.JS version in `package.json`

---

src-test/test.js
src/index.js
test-positive/mermaid.md

Handles empty newlines before and after diagrams in Markdown.
For example, the following Markdown:
````markdown
My text.
```mermaid
my diagram
```
````
Should get converted to:
```markdown
My text.
```
However, currently, the empty newline is removed.
We can fix this by making sure that our Regex ignores newlines outside of the Mermaid diagram code.
Fixes: 9d7b4b29d3dfcaa21f4639314aadf09fe4ccbe19 (where bug was introduced)
Fixes: https://github.com/mermaid-js/mermaid-cli/issues/413
Instead of using `\s` to find all whitespace, I'm instead using `[^\S\n]` to find anything that is not a non-whitespace character nor `\n` (basically any `\s` that is not `\n`).
In the future, it might be worth instead using https://github.com/remarkjs/remark to handle Markdown parsing, since there are probably …

fix: handle empty newlines before diagrams in md

---

DockerfileBuild

Following our discussion on issue #435

FIX #435: Use absolute path for the entrypoint

---

README.md
src-test/test.js
src/index.js

Improves how `mmdc` handles `stdin` inputs.
Currently, running `mmdc` exits with an error if it cannot find an stdin. However, it does this by checking if the stdin is a FIFO, which is only true in some cases.
(it seems to fail on Windows and other non-bash shells).
I've changed `mmdc` to always read from stdin if there is no `--input`. However, it prints a warning:
```console
user@pc:~/mermaid-cli $ node src/cli.js
No input file specfied, reading from stdin. If you want to specify an input file, please use `-i <input>.` You can use `-i -` to read from stdin and to suppress this warning.
```
To suppress this warning, you can run mmdc with `--input -` (this is what many CLI tools, like `cat` does).
Resolves https://github.com/mermaid-js/mermaid-cli/issues/468 (although I haven't tested it, …

Improve `stdin` input handling on (fixes Windows)

---

src-test/test.js
src/index.js
test-positive/mermaid.md

Support trailing whitespace on the same line and after the opening
`` ```mermaid block ``, by adding a `[^\S\n]*` to the regex.
`[^\S\n]` is anything that is `\s` (whitespace char), except `\n`.
Resolves #487
I wonder if we should just give up on trying to parse Markdown ourselves and switch to using something like [Remark](https://github.com/remarkjs/remark) to do it for us.
Make sure you

Support trailing spaces after '```mermaid'

---

index.html
package.json
yarn.lock

The mermaid-cli project is currently using the very old and very deprecated [@fontawesome/fontawesome-free-webfonts][1] package that hasn't been updated in 5 years (since 2018-05-10).
According to [fontawesome's `UPGRADING.md` guide][2], the new package we should switch to is [@fontawesome/fontawesome-free][3].
Although fontawesome v5 adds official JavaScript support, I've kept the same CSS imports we had previously, in order to avoid the risk of breaking anything.
The fontawesome license has slightly changed, but as long as we keep their licensing info in the files in `dist/` (which we do), then it's all fine, see [LICENSE.txt][4].
[1]: https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts
[2]: https://github.com/FortAwesome/Font-Awesome/blob/5.x/UPGRADING.md#50x-to-510 …

build(deps-dev): switch to fontawesome v5

---

src/index.js

The documentation of the CLI indicates that pdfFit takes a parameter. This is confusing, because pdfFit is simply a boolean.
This PR updates the documentation to indicate that pdfFit is a boolean.
Make sure you

Update documentation for `--pdfFit` to accurately reflect it as a boolean

---

.github/workflows/compile-mermaid.yml

It looks like the **Build and Push Image(s)** step is a bit slow. Sometimes, it times out, as it takes 25–30 minutes.
Bumping the timeout to 90 minutes means that hopefully the CI run will stop timing out.
I picked 90 minutes since I'm guessing a slow run will take 35 to 40 minutes, and I usually like to have a 2x headroom on timeouts, since you never know when DockerHub/GitHub/Alpine will have a slow day.
**Example failing CI runs due to timeout**:
- https://github.com/mermaid-js/mermaid-cli/actions/runs/4542097531/jobs/8005083565
Make sure you

ci(compile-mermaid): bump timeout to 90 minutes

---

src-test/test.js

It looks like some of the jest tests are very occasionally timing out in CI.
This might be because GitHub Actions is slower now, or that Mermaid is slower with the newer diagrams.
Doubling the current jest timeout from 30s to 60s should fix this.
Should fix the following error:
> ```
>   ● mermaid-cli › the .svg extension should be added to .md files
> 
>     thrown: "Exceeded timeout of 30000 ms for a test.
>     Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
> 
>       225 |   }, timeout)
>       226 |
>     > 227 |   test('the .svg extension should be added to .md files', async () => {
>           |   ^
>       228 |     const expectedOutputFiles = [1, 2, 3, 4, 5, 6, 7, 8, 9].map((i) => …
```

test: increase jest test timeout to 60s

---

index.html
package.json
src/index.js
yarn.lock

Since [Mermaid v9.4.0][1], the `@mermaid-js/mermaid-mindmap` package is no longer needed, since it has been integrated as part of the main mermaid package.
See: https://mermaid.js.org/syntax/mindmap.html#integrating-with-your-library-website
See: https://github.com/mermaid-js/mermaid/commit/71e4f1152b96fe716b156f1ab687fd01e724715b
[1]: https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0
Removing this package decreases the size of `mermaid-cli`'s `dist/index.html` by about 8%!
```
dist/index.html                          5,241.86 kB │ gzip: 2,148.61 kB
```
```
dist/index.html                          4,841.83 kB │ gzip: 2,020.65 kB
```
N/A
Make sure you
- We already have mindmap tests!

build: remove dependency on mermaid-mindmap pkg

---

src-test/test.js
src/index.js
test-positive/classDiagram-v2.mmd

Use the [`mermaid.render()`](https://mermaid.js.org/config/usage.html#api-usage) function instead of the `mermaid.run()` function to parse Mermaid diagram definitions directly, without going through HTML first.
- fixes the issue of HTML removing newlines
- Resolves https://github.com/mermaid-js/mermaid-cli/issues/532
- means we get better error messages!
Currently, `mermaid-cli` renders mermaid diagrams by:
```mermaid
flowchart LR
subgraph a ["Removes newlines!!!"]
div["HTML &lt;div&gt;"]
end
MMD --> div["HTML &lt;div&gt;"]
div -->|"mermaid.run()"| svg["HTML &lt;svg&gt;"]
```
However, when converting the mmd code to HTML `<div>`, newlines and whitespace formatting may get removed. For the majority of diagrams, this is no issue, but for some diagrams (e.g. `classDiagram`), whitespace does …

Use `mermaid.render()` instead of `mermaid.run()` API to avoid removing whitespace from diagrams

---

test-positive/flowchart3.mmd

Mermaid v10.2.0 changed some behavior for `htmlLabels` with embedded SVG images. The `width=100%` is now set in the node CSS, which normally scales the images to the width of the text, but for this SVG, it seems to crop it. See https://github.com/mermaid-js/mermaid/issues/4455.
Setting a well-defined `viewBox` attribute to our SVG fixes this.
Resolves the visual regression discussed in https://github.com/mermaid-js/mermaid-cli/pull/541#issuecomment-1575789802
Thanks to @Valentine14th for finding and recommending this fix! I've credited them as a co-author.
Make sure you

test: update flowchart3 test case

---

src/index.js

Hide the "Puppeteer old Headless deprecation warning" that is printed in Puppeteer v19.11.0 or later, when `headless: "new"` is not used.
[1]: https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/node/ChromeLauncher.ts#L50
[2]: https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/node/ChromeLauncher.ts#L213-L215
Resolves https://github.com/mermaid-js/mermaid-cli/issues/544
Using `headless: "new"` is the official way of hiding this warning, but it currently isn't very stable in Puppeteer v19.11.0 (see https://github.com/mermaid-js/mermaid-cli/issues/544#issuecomment-1575808425), and we can't upgrade to Puppeteer v20 until mermaid-cli drops Node.JS v14 support.
Instead, we …

Hide "Puppeteer old Headless deprecation warning"

---

README.md

Improved podman instructions.
Added `Use Podman` section to the `Alternative Installations` section of the readme.
Make sure you

Improve podman instructions for alternative installations

---

index.html
package.json
src/index.js
test-positive/zenuml.mmd
yarn.lock

Mermaid now has support for ZenUML diagrams, but it requires using a Mermaid plugin diagram, see https://mermaid.js.org/syntax/zenuml.html
ZenUML adds about 700 KiB to our `dist/index.html` file, or about 200 KiB when gzipped.
Resolves #564
Adding support for ZenUML diagrams is just like how we previously added support for mindmap diagrams in PR https://github.com/mermaid-js/mermaid-cli/pull/424, so please see discussion in that PR for design decisions.
By the way, I had to manually limit the version of `antlr4` to `~4.11.0`, since v4.12.0 (in commit https://github.com/antlr/antlr4/commit/2c75e642796718273fd215b03a310d4958319bad) drops NodeJS v14 support.
**ZenUML adds about 700 KiB to our `dist/index.html` file, or about 200 KiB when gzipped.** Additionally, it takes about 2.5 seconds …

feat: add support for @mermaid-js/mermaid-zenuml

---

package.json

Currently, the TypeScript types for this module only support the `node10` TypeScript module resolution mode.
Now, `node10`, `node16` (ESM only), and `bundler` all work, according to https://arethetypeswrong.github.io/, see https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution
Resolves https://github.com/mermaid-js/mermaid-cli/issues/628
Resolves https://github.com/mermaid-js/mermaid-cli/issues/633
@andrewshawcare, I've listed you as a co-author for this commit since the content is from your recommended patch in https://github.com/mermaid-js/mermaid-cli/issues/633! Let me know if you're not comfortable with this, or if you'd prefer to make your own PR for this contribution!
Make sure you
- Manually tested by running `yarn pack` and checking the contents with …

Fix TypeScript types to support `node16` and `bundler` `moduleResolution` modes

---

src-test/test.js
src/index.js

Add a new option `-I, --svgId [svgId]` to set the id attribute of the `<svg>` element to be rendered.
This is useful when the output is used as a part of HTML, because Mermaid CSS pollutes the global CSS with the id.
`svgId || 'my-svg'` to use the old id as default. `||` instead of `??` to avoid empty id and for better compatibility.
Make sure you

feat: add svgId option

---

src/index.js

The TFS 2022 uses ::: as highlight characters of the mermaid graph viewer. Now this tool able to recognize this format as well

add ::: highlight signal chars

---

src/index.js

Whether or not the used fonts have been loaded, affects the layout of the boxes that Mermaid renders. For consistent results, fonts must be loaded before the diagrams are rendered.
This was taken from [`mermaid-isomorphic`](https://github.com/remcohaszing/mermaid-isomorphic/blob/v2.1.2/src/mermaid-isomorphic.ts#L142). You may want to leverage that package instead.
Resolves #539
This preloads all fonts in the document.
Make sure you

Load all fonts before rendering

---

src/index.js
test-positive/mermaidless-markdown-file.md

Skip launching puppeteer until it's actually needed.
Running mermaid-cli on a markdown file without any mermaid code blocks shouldn't launch puppeteer, if it's unnecessary.
Resolves https://github.com/mermaid-js/mermaid-cli/issues/694
N/A
Make sure you

perf: skip launching puppeteer when not needed

---

DockerfileBuild

Chromium 128.0.6613.84-r0 (used in Alpine 3.20) seems to be having issues with puppeteer/mermaid-cli, so we can't use it yet.
Resolves failing CI in recent PRs (see https://github.com/mermaid-js/mermaid-cli/actions/workflows/compile-mermaid.yml), e.g.:
```console
$ bash run-tests.sh test-positive mermaid-js/mermaid-cli/mermaid-cli:10.9.2-PullRequest0733.12
Generating single mermaid chart
ProtocolError: Page.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
at new Callback (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:58:35)
at CallbackRegistry.create (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:103:26)
at Connection._rawSend …
```

build: use `node:18.20-alpine3.19` in Docker build

---

src-test/test.js
src/index.js

Support writing to `stdout` if the user explicitly specifies `-`.  In case of no output format, it is assumed to be `svg` and a warning is displayed.
Resolves #683
For the sake of making the code more readable, I'm using explicit `'/dev/stdout'`.  This is just a personal preference and   doesn't have anything to do with the platform.
I have also disabled writing to `stdout` if the input is markdown.
Make sure you

Support using stdout

---

src/index.js

Currently, SVGs are returned as `Buffer`s from `renderMermaid()`, which is almost compatible with `UInt8Array`, but not 100%, which was causing TypeScript 5.6 to throw an error.
See: https://github.com/mermaid-js/mermaid-cli/pull/746
This should resolve the CI failure in https://github.com/mermaid-js/mermaid-cli/pull/746
N/A
Make sure you
- Will be added by #746

fix: return SVGs as UInt8Array instead of `Buffer`

---

src/index.js

Allow passing either a Puppeteer Browser or a Puppeteer BrowserContext to `renderMermaid`, as both work fine.
See: https://pptr.dev/api/puppeteer.browser
See: https://pptr.dev/api/puppeteer.browsercontext
N/A
Make sure you

fix: broaden `renderMermaid` browser type

---

Dockerfile

Chromium 128.0.6613.84-r0 (used in Alpine 3.20) seems to be having issues with puppeteer/mermaid-cli (especially in GitHub Actions), so we can't use it yet.
See: 294af9f99ee91243209ba14a6b05b46fca1515c0
Resolves https://github.com/mermaid-js/mermaid-cli/issues/762
N/A
Make sure you
- I believe we already have E2E tests that cover this, e.g. https://github.com/mermaid-js/mermaid-cli/actions/runs/11211689722/job/31161097388 and https://github.com/mermaid-js/mermaid-cli/blob/082fd7fbfcef41a8d968a895ea45b68dde75110a/.github/workflows/release-publish.yml#L93-L96

build: use `node:18.20-alpine3.19 in Docker

---

package-lock.json
package.json
vite.config.ts

Compile JavaScript code as an IIFE, allowing us to avoid needing to inline anything.
This makes the code about 10% faster for me (tests run in 105s instead of 120s), and the size on the bundle went from 4MiB to 3.5MiB.
Additionally, **I've finally figured out the issue that was sometimes causing the FontAwesome icons to load incorrectly**: sometimes Puppeteer was parsing the CSS FontAwesome as Latin-1 instead of UTF-8! Explicitly setting the script to have `charset="utf-8"` seems to fix this!
Resolves https://github.com/mermaid-js/mermaid-cli/pull/699. Resolves https://github.com/mermaid-js/mermaid-cli/pull/700
Instead of bundling everything into a single giant `index.html` file, it's more efficient to have separate files, as otherwise, some files (e.g. the `.woff2` font files), need to …

build: skip bundling fonts

---

index.html
package-lock.json
package.json
src/index.js

Instead of bundling the `@mermaid-js/mermaid-zenuml` package ourselves, we can let the user install their own version of it.
This lowers the size of the `dist/index.html` file by about 1.3 MB:
```console
$ npx vite build
vite v4.5.5 building for production...
✓ 656 modules transformed.
dist/index.html  5,627.39 kB │ gzip: 2,451.54 kB
✓ built in 9.67s
```
```console
$ npx vite build
vite v4.5.5 building for production...
✓ 638 modules transformed.
dist/index.html  4,340.56 kB │ gzip: 2,124.28 kB
✓ built in 6.63s
```
Make sure you

perf: skip bunding Mermaid ZenUML

---

.github/workflows/release-publish.yml
package.json
scripts/version.js
src/index.js
src/version.js

- Create version file of `src/version.js`.
- Changed version reference from package.json to version.js.
- Added step to update src/version.js at github actions.
Resolves #796 
Using JSON Modules proved difficult, so we decided to create a version constant file
- See : #797 
Make sure you

Create version file and delete loading package.json version

---

tsconfig.json

It looks like the default `rootDir` was `"."`, but for some reason, adding the `src/version.js` file changed the `rootDir` to `"./src/"`.
I'm not sure why this is, looking at the TypeScript `tsconfig` reference docs for `rootDir`: <https://www.typescriptlang.org/tsconfig/#rootDir>, they say:
> **Default**: The longest common path of all non-declaration input files.
Which should have already been `./src/`?
Regardless, I've explicitly set `rootDir: "."` to generate the types at `dist-types/src/index.d.ts` instead of the `dist-types/index.d.ts` it's being exported to since 9a42e3c408be34df19c58735eea444d3b0ac37c9.
Fixes: 9a42e3c408be34df19c58735eea444d3b0ac37c9
Fixes: https://github.com/mermaid-js/mermaid-cli/issues/803
N/A
Make sure you

fix(types): correct `rootDir` in tsconfig.json

---

.github/workflows/compile-mermaid.yml
.github/workflows/test.yml

Ubuntu 24.04 has stricter AppArmor policies that prevent Puppeteer from running, with an error like:
> Failed to launch the browser process!
> [0109/235031.343250:FATAL:zygote_host_impl_linux.cc(128)] No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
We can use [`aa-exec`][1] to explicitly set the `chrome` policy and get it …

ci: use `aa-exec` to fix Puppeteer on Ubuntu 24.04 CI

---

package-lock.json

Add `integrity` field where missing the `package-lock.json`. This enforces the dependency checksum and allows for Nix packaging.
Resolves #828 
I used https://github.com/jeslie0/npm-lockfile-fix script to fill in the integrity fields. Packages install on my machine.
Make sure you

Add missing package integrity

---

run-tests.sh
src-test/test.js
src/index.js
test-positive/architecture-diagram-logos.mmd

Support Iconify icon packs that are used in `architecture-beta`.
Resolves https://github.com/mermaid-js/mermaid-cli/issues/764, https://github.com/mermaid-js/mermaid-cli/issues/805
I have the same issue described in the #764 and #805. I think it makes sense to add the way similar as the comment https://github.com/mermaid-js/mermaid-cli/issues/764#issuecomment-2448695522 to the upstream because it doesn't have any side effect if it's lazy load.
Although it might be reasonable to support any icon packs with a command line option, it would be good to support commonly used `logos` and `mdi` first as [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) supports them.
Make sure you

Add Iconify support

---

.gitignore
CONTRIBUTING.md
package.json
run-tests.sh
src-test/test.js
src/index.js

feat: artefacts option

---

package-lock.json
run-tests.sh
src-test/test.js
src/index.js.bak
test-positive/flowchart4.mmd

`iconPacks` option allows only to target icons stored in unpkg
There are icons available outside of unpkg (as the ones used on mermaid chart  playground)
added `iconPacksNamesAndUrls` option that looks like `iconPacks` option but gives the opportunity to use any valid Iconify json file (example : azure**#**https://raw.githubusercontent.com/NakayamaKento/AzureIcons/refs/heads/main/icons.json)

feat: add iconPacksNamesAndUrls option in order to be able to use icons outside unpkg
