.github/workflows/release-publish.yml, package.json
Github action for publishing mermaid-cli packages to npm registry.
=> Publish release workflow

.github/workflows/release-publish.yml
=> Fix mermaid-cli build error

Dockerfile
Parameterize mermaid-cli version
=> Parameterize mermaid-cli version

.github/pr-labeler.yml, .github/workflows/pr-labeler.yml
=> Add workflow to label PRs

.github/workflows/compile-mermaid.yml, README.md
Integrate with percy.io for e2e testing.
=> Working on percy integration

.github/workflows/compile-mermaid.yml
Replace call to docker image with github action
=> Use percy-upload action instead

.github/workflows/compile-mermaid.yml
=> Remove github registry and add PDF tests

README.md
document running with https://www.npmjs.com/package/npx in the readme
=> show how to run with npx

.github/workflows/compile-mermaid.yml, .github/workflows/release-publish.yml, README.md, src-test/test.js, src/index.js
Accept input from STDIN.
Resolves #47
If user pipes input from STDIN and does not specify a file name, the file 'out.svg' will be created in the current directory.
Make sure you
=> Feature/Take input from STDIN

.github/workflows/compile-mermaid.yml, .github/workflows/release-publish.yml, GitVersion.yml, package.json, yarn.lock
We will integrate GitVersion into the build pipeline. The benefits of having GitVersion: https://gitversion.net/docs/why
Make sure you
- [/] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [/] :computer: have added unit/e2e tests (if appropriate) 
- [/] :bookmark: targeted `master` branch
=> Integrate GitVersion to the build/release pipeline

.github/workflows/compile-mermaid.yml
Use GitVersion action intead of docker image
=> Use GitVersion action intead of docker image

.github/workflows/compile-mermaid.yml, run-tests.sh
The number of tests is growing. We want to keep them in a separate file.
=> Move tests to another file

src/index.js
=> Added process.title

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, building.md, docs/linux-sandbox-issue.md
Brief description of the content of your PR.
Linting and grammatical fixes in markdown
Used `markdownlint` and rest by hand
Make sure you
=> Better markdown and issue template config

README.md
I had a hard time initially with trying out the container, because it wasn't documented on hub.docker.com how to use it. This will hopefully remedy that for others.
I describe the simplest use of having a diagram defined in a text file, and how to use the Docker container to process it. I couldn't find a conventional file extension for "mermaid files", so I chose .mmd. Feel free to modify.
I didn't create an issue tracker. I hope that's OK.
=> More detailed instruction to get going with Docker

README.md
The README did not have clear enough examples to really show off the
awesomeness of this project. So I added a few examples that will quickly
show how useful this tool is.
Also there were just a few very long lines in the README so I formatted
them to around 80 characters.
Just an update to the README which I feel will make it more clear and enticing!
Resolves #<your issue id here>
Make sure you
=> Added example usage and formatted long lines in README

DockerfileBuild
Fix https://github.com/actions/virtual-environments/issues/732
Resolves #<your issue id here>
Make sure you
=> puppeteer misses shared library libgbm

.github/workflows/compile-mermaid.yml, Dockerfile, DockerfileBuild, install-dependencies.sh
Go away from using root as the container user
Resolves #<your issue id here>
User memraidcli user instead of root
=> Introduce mermaidcli user

install-dependencies.sh
Adds two more packages with fonts, one for emojis and another for Japanese characters. Also updates fonts-liberation to fonts-liberation2
Resolves #131 and #93 
Make sure you
=> docker: added fonts with emojis and japanese characters

.github/dependabot.yml
=> chore(ci) : update github-actions with dependabot

.github/workflows/pr-labeler.yml
This is fixing the pr labeling workflow
Make sure you
=> Fix pr-labeler configuration

src/index.js
=> Provide help text if no input arguments

.github/dependabot.yml
Resolves #<your issue id here>
Make sure you
=> define dependabot schedule

src/index.js
https://stackoverflow.com/questions/69081410/error-err-require-esm-require-of-es-module-not-supported
=> Use ESM imports now

src/index.js
API: https://puppeteer.github.io/puppeteer/docs/puppeteer.pdfoptions
=> Fix export pdf backgroundColor not transparent

.github/workflows/release-publish.yml
=> Update node version

src/index.js
=> Allow output paths to contain dots

src-test/test.js, src/index.js
Run yarn standard --fix to fix lint errors
=> Run yarn standard --fix

README.md, docs/already-installed-chromium.md
Closes #331 
Co-authored-by: User @aloisklink
=> How to setup up mermaid to use already installed chromium (doc update)

README.md
Document the decision taken in https://github.com/mermaid-js/mermaid-cli/issues/288
=> Discontinue brew support

.github/workflows/compile-mermaid.yml, README.md, docs/reviewing.md
=> Fixing typos

test-positive/git-graph.mmd, test-positive/mermaid.md
Add a test case for git graphs.
```mermaid
gitGraph
commit
commit
branch feature
commit
checkout main
merge feature
```
Somebody reported that git graphs wasn't working in `mermaid-cli`, so I've added a test just to make sure it is working, and it seems like it is!
I've replaced diagram 2 in the `test-positive/mermaid.md`, since it's identical to diagram 7
Make sure you
=> test: add a basic git graph test

README.md
Add some version badges to the README.md
The new list of open-source badges are:
[![npm version](https://img.shields.io/npm/v/@mermaid-js/mermaid-cli)](https://www.npmjs.com/package/@mermaid-js/mermaid-cli)
[![node-lts (scoped)](https://img.shields.io/node/v-lts/@mermaid-js/mermaid-cli)](https://www.npmjs.com/package/@mermaid-js/mermaid-cli)
[![Docker Image Version (latest semver)](https://img.shields.io/docker/v/minlag/mermaid-cli?label=Dockerhub)](https://hub.docker.com/r/minlag/mermaid-cli)
[![Build, test and deploy mermaid-cli Docker image](https://github.com/mermaid-js/mermaid-cli/actions/workflows/compile-mermaid.yml/badge.svg)](https://github.com/mermaid-js/mermaid-cli/actions/workflows/compile-mermaid.yml)
[![This project is using Percy.io for visual regression …
=> docs: add npm/dockerhub version badges

Dockerfile, DockerfileBuild, README.md
The PR replaces PR https://github.com/mermaid-js/mermaid-cli/pull/470
Following our discussion on issue https://github.com/mermaid-js/mermaid-cli/issues/435
=> Change docker workdir

test-positive/timeline.mmd
Add a basic test for timeline diagrams (added by Mermaid v9.4.0), taken from the official Mermaid docs:
https://github.com/mermaid-js/mermaid/blob/v9.4.0/packages/mermaid/src/docs/syntax/timeline.md#an-example-of-a-timeline
Resolves https://github.com/mermaid-js/mermaid-cli/issues/493 (timeline diagrams were already working, we just hadn't added a test for it)
This is what the diagram looks like:
Make sure you
=> Add a basic test for timeline diagrams

src-test/test.js, src/index.js
Correct a typo in index.js
Make sure you
=> Correct a typo in the "no input file" warning

README.md
Remove duplicate installation instructions. They were probably left after moving from yarn to npm.
Make sure you
=> Remove duplicate instructions in "Install locally" section

.github/stale.yml, README.md, docs/docker-permission-denied.md, src-test/test.js, src/index.js, test-positive/timeline.mmd
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling)
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/mermaid-cli/actions/runs/14534700383#summary-40780769251
- Resolves #892 
Make sure you
=> chore: Fix spelling
